from . import Modeler, Schematic, InterfacePCBS, Parameters
from typing import Protocol

class IProject(Protocol):
    def get_modeler(self) -> Modeler: ...

    def get_schematic(self) -> Schematic: ...

    def get_interface_pcbs(self) -> InterfacePCBS: ...

    def get_parameters(self) -> Parameters: ...

    def get_messages(self) -> list: ...

    def get_last_message_text(self) -> str: ...
