from typing import Protocol

class IQuietModeController(Protocol):
    def store_quiet_mode(self) -> None: ...

    def restore_quiet_mode(self) -> None: ...

    def store_and_disable_quiet_mode(self) -> None: ...

    def store_and_enable_quiet_mode(self) -> None: ...

    def set_quiet_mode(self, enabled: bool = True) -> None: ...

    def is_in_quiet_mode(self) -> bool: ...
