from . import HistoryListGenerator, VBATypeName, IQuietModeController
from typing import Optional, Union, Protocol

class IVBAProvider(Protocol):
    def get_history_list_generator(self) -> HistoryListGenerator: ...

    def run_vba(self, vba_code: str) -> bool: ...

    def invoke_function(self, function_name: str, *args: Union[str, int, float, bool]) -> bool: ...

    def invoke_method(
        self, object_name: str, function_name: str, *args: Union[str, int, float, bool]): ...

    def query_vba(self, vba_code: str) -> Optional[str]: ...

    def query_function(
        self, function_name: str, *args: Union[str, int, float, bool]) -> Optional[str]: ...

    def query_method(
        self, object_name: str, function_name: str,
        *args: Union[str, int, float, bool]) -> Optional[str]: ...

    def query_function_t(
        self, function_name: str, return_type: Optional[VBATypeName],
        *args: Union[str, int, float, bool, VBATypeName]) -> tuple: ...

    def query_method_t(
        self, object_name: str, function_name: str, return_type: Optional[VBATypeName],
        *args: Union[str, int, float, bool, VBATypeName]) -> tuple: ...

    def get_quiet_mode_controller(self) -> IQuietModeController: ...
